/**
 * ESM wrapper for the BLSCT WASM module
 * 
 * This wrapper provides ESM-compatible exports for the CommonJS WASM module,
 * enabling seamless usage with modern bundlers (Vite, Webpack, Rollup, etc.)
 * and browser ESM contexts.
 * 
 * The underlying blsct.js file is generated by Emscripten with CommonJS exports.
 * This wrapper re-exports it as an ESM default export.
 */

// Calculate the path to blsct.js relative to this file
const blsctJsUrl = new URL('./blsct.js', import.meta.url).href;

let BlsctModuleFactory = null;
let initPromise = null;

/**
 * Initialize the module factory by loading the underlying CommonJS module
 */
async function initFactory() {
  if (BlsctModuleFactory) {
    return BlsctModuleFactory;
  }
  
  if (initPromise) {
    return initPromise;
  }
  
  initPromise = (async () => {
    try {
      // Dynamic import with webpackIgnore to prevent bundler transformation
      const module = await import(/* webpackIgnore: true */ blsctJsUrl);
      
      // Handle various export formats
      let factory = module.default;
      
      if (typeof factory !== 'function') {
        // Try named export
        if (typeof module.BlsctModule === 'function') {
          factory = module.BlsctModule;
        }
        // Try the module itself
        else if (typeof module === 'function') {
          factory = module;
        }
        // Search for any function export
        else if (typeof module === 'object' && module !== null) {
          for (const key of Object.keys(module)) {
            if (typeof module[key] === 'function') {
              factory = module[key];
              break;
            }
          }
        }
      }
      
      if (typeof factory !== 'function') {
        throw new Error(
          `BlsctModule factory not found. Module type: ${typeof module}, ` +
          `keys: ${Object.keys(module || {}).join(', ')}`
        );
      }
      
      BlsctModuleFactory = factory;
      return factory;
    } catch (e) {
      // Fallback: check for global BlsctModule (UMD pattern from script tag)
      if (typeof globalThis !== 'undefined' && typeof globalThis.BlsctModule === 'function') {
        BlsctModuleFactory = globalThis.BlsctModule;
        return BlsctModuleFactory;
      }
      throw new Error('Failed to load BlsctModule: ' + e.message);
    }
  })();
  
  return initPromise;
}

/**
 * BLSCT WASM Module Factory
 * 
 * Call this function with optional configuration to instantiate the WASM module.
 * 
 * @param {Object} [config] - Optional configuration object
 * @param {function} [config.locateFile] - Function to locate WASM binary
 * @param {ArrayBuffer} [config.wasmBinary] - Pre-loaded WASM binary
 * @param {function} [config.print] - Custom print function for stdout
 * @param {function} [config.printErr] - Custom print function for stderr
 * @returns {Promise<Object>} The initialized WASM module instance
 * 
 * @example
 * import BlsctModuleFactory from 'navio-blsct/wasm/blsct.mjs';
 * const module = await BlsctModuleFactory();
 * module._init();
 */
export default async function(config) {
  const factory = await initFactory();
  return factory(config);
}

// Named export
export { initFactory as BlsctModuleFactory };

