name: 'C#: Publish doc website'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ffi/csharp/Blsct.cs'
      - 'ffi/csharp/blsct.i'
      - 'ffi/csharp/docs/**'
      - '.github/workflows/csharp-publish-doc.yml'

concurrency:
  group: gh-pages-deploy
  cancel-in-progress: false

permissions:
  contents: write


jobs:
  csharp-publish-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            10.0.x

      - name: Install SWIG
        run: |
          sudo apt-get update
          sudo apt-get install -y swig

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Build documentation
        run: |
          cd ffi/csharp/docs
          docfx docfx.json

      - name: Deploy C# docs to /csharp
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ffi/csharp/docs/_site
          publish_branch: gh-pages
          destination_dir: csharp
          keep_files: true
